#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Tradutor Manual Português-Espanhol para DOCX
Preserva formatação, imagens e estrutura original
Sem dependência de APIs externas
"""

import os
import sys
from docx import Document
from docx.shared import Inches, Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH
import re
from datetime import datetime

class TradutorManualEspanhol:
    def __init__(self):
        self.dicionario_pt_es = {
            # Palavras comuns
            'e': 'y',
            'de': 'de',
            'do': 'del',
            'da': 'de la',
            'dos': 'de los',
            'das': 'de las',
            'em': 'en',
            'no': 'en el',
            'na': 'en la',
            'nos': 'en los',
            'nas': 'en las',
            'para': 'para',
            'por': 'por',
            'com': 'con',
            'sem': 'sin',
            'que': 'que',
            'não': 'no',
            'sim': 'sí',
            'muito': 'muy',
            'mais': 'más',
            'menos': 'menos',
            'bem': 'bien',
            'mal': 'mal',
            'grande': 'grande',
            'pequeno': 'pequeño',
            'novo': 'nuevo',
            'velho': 'viejo',
            'bom': 'bueno',
            'mau': 'malo',
            'primeiro': 'primero',
            'último': 'último',
            'todo': 'todo',
            'todos': 'todos',
            'toda': 'toda',
            'todas': 'todas',
            'cada': 'cada',
            'outro': 'otro',
            'outra': 'otra',
            'outros': 'otros',
            'outras': 'otras',
            'mesmo': 'mismo',
            'mesma': 'misma',
            'mesmos': 'mismos',
            'mesmas': 'mismas',
            
            # Verbos comuns
            'ser': 'ser',
            'estar': 'estar',
            'ter': 'tener',
            'haver': 'haber',
            'fazer': 'hacer',
            'dizer': 'decir',
            'ir': 'ir',
            'vir': 'venir',
            'ver': 'ver',
            'dar': 'dar',
            'saber': 'saber',
            'poder': 'poder',
            'querer': 'querer',
            'ficar': 'quedarse',
            'chegar': 'llegar',
            'partir': 'partir',
            'começar': 'empezar',
            'terminar': 'terminar',
            'trabalhar': 'trabajar',
            'estudar': 'estudiar',
            'aprender': 'aprender',
            'ensinar': 'enseñar',
            'falar': 'hablar',
            'escutar': 'escuchar',
            'ler': 'leer',
            'escrever': 'escribir',
            'pensar': 'pensar',
            'sentir': 'sentir',
            'amar': 'amar',
            'gostar': 'gustar',
            'odiar': 'odiar',
            'comer': 'comer',
            'beber': 'beber',
            'dormir': 'dormir',
            'acordar': 'despertar',
            'levantar': 'levantar',
            'sentar': 'sentar',
            'andar': 'caminar',
            'correr': 'correr',
            'voar': 'volar',
            'nadar': 'nadar',
            'jogar': 'jugar',
            'ganhar': 'ganar',
            'perder': 'perder',
            'comprar': 'comprar',
            'vender': 'vender',
            'pagar': 'pagar',
            'receber': 'recibir',
            'enviar': 'enviar',
            'mandar': 'mandar',
            'ajudar': 'ayudar',
            'precisar': 'necesitar',
            'usar': 'usar',
            'utilizar': 'utilizar',
            'encontrar': 'encontrar',
            'procurar': 'buscar',
            'perguntar': 'preguntar',
            'responder': 'responder',
            'explicar': 'explicar',
            'entender': 'entender',
            'compreender': 'comprender',
            'conhecer': 'conocer',
            'lembrar': 'recordar',
            'esquecer': 'olvidar',
            'decidir': 'decidir',
            'escolher': 'elegir',
            'preferir': 'preferir',
            'aceitar': 'aceptar',
            'recusar': 'rechazar',
            'permitir': 'permitir',
            'proibir': 'prohibir',
            'obrigar': 'obligar',
            'conseguir': 'conseguir',
            'tentar': 'intentar',
            'esperar': 'esperar',
            'acontecer': 'suceder',
            'mudar': 'cambiar',
            'melhorar': 'mejorar',
            'piorar': 'empeorar',
            'crescer': 'crecer',
            'diminuir': 'disminuir',
            'aumentar': 'aumentar',
            'abrir': 'abrir',
            'fechar': 'cerrar',
            'entrar': 'entrar',
            'sair': 'salir',
            'voltar': 'volver',
            'retornar': 'regresar',
            'continuar': 'continuar',
            'parar': 'parar',
            'acabar': 'acabar',
            'morrer': 'morir',
            'nascer': 'nacer',
            'viver': 'vivir',
            'existir': 'existir',
            
            # Substantivos comuns
            'pessoa': 'persona',
            'pessoas': 'personas',
            'homem': 'hombre',
            'mulher': 'mujer',
            'criança': 'niño',
            'menino': 'niño',
            'menina': 'niña',
            'pai': 'padre',
            'mãe': 'madre',
            'filho': 'hijo',
            'filha': 'hija',
            'irmão': 'hermano',
            'irmã': 'hermana',
            'avô': 'abuelo',
            'avó': 'abuela',
            'tio': 'tío',
            'tia': 'tía',
            'primo': 'primo',
            'prima': 'prima',
            'amigo': 'amigo',
            'amiga': 'amiga',
            'família': 'familia',
            'casa': 'casa',
            'apartamento': 'apartamento',
            'quarto': 'habitación',
            'sala': 'sala',
            'cozinha': 'cocina',
            'banheiro': 'baño',
            'jardim': 'jardín',
            'rua': 'calle',
            'cidade': 'ciudad',
            'país': 'país',
            'mundo': 'mundo',
            'terra': 'tierra',
            'céu': 'cielo',
            'sol': 'sol',
            'lua': 'luna',
            'estrela': 'estrella',
            'água': 'agua',
            'fogo': 'fuego',
            'ar': 'aire',
            'vento': 'viento',
            'chuva': 'lluvia',
            'neve': 'nieve',
            'tempo': 'tiempo',
            'dia': 'día',
            'noite': 'noche',
            'manhã': 'mañana',
            'tarde': 'tarde',
            'semana': 'semana',
            'mês': 'mes',
            'ano': 'año',
            'hora': 'hora',
            'minuto': 'minuto',
            'segundo': 'segundo',
            'vida': 'vida',
            'morte': 'muerte',
            'nascimento': 'nacimiento',
            'trabalho': 'trabajo',
            'escola': 'escuela',
            'universidade': 'universidad',
            'livro': 'libro',
            'página': 'página',
            'palavra': 'palabra',
            'frase': 'frase',
            'texto': 'texto',
            'história': 'historia',
            'música': 'música',
            'filme': 'película',
            'foto': 'foto',
            'imagem': 'imagen',
            'cor': 'color',
            'branco': 'blanco',
            'preto': 'negro',
            'vermelho': 'rojo',
            'azul': 'azul',
            'verde': 'verde',
            'amarelo': 'amarillo',
            'laranja': 'naranja',
            'rosa': 'rosa',
            'roxo': 'morado',
            'cinza': 'gris',
            'marrom': 'marrón',
            'número': 'número',
            'zero': 'cero',
            'um': 'uno',
            'dois': 'dos',
            'três': 'tres',
            'quatro': 'cuatro',
            'cinco': 'cinco',
            'seis': 'seis',
            'sete': 'siete',
            'oito': 'ocho',
            'nove': 'nueve',
            'dez': 'diez',
            'cem': 'cien',
            'mil': 'mil',
            'milhão': 'millón',
            'dinheiro': 'dinero',
            'real': 'real',
            'euro': 'euro',
            'dólar': 'dólar',
            'comida': 'comida',
            'pão': 'pan',
            'arroz': 'arroz',
            'feijão': 'frijol',
            'carne': 'carne',
            'peixe': 'pescado',
            'fruta': 'fruta',
            'verdura': 'verdura',
            'leite': 'leche',
            'café': 'café',
            'chá': 'té',
            'vinho': 'vino',
            'cerveja': 'cerveza',
            'carro': 'coche',
            'ônibus': 'autobús',
            'trem': 'tren',
            'avião': 'avión',
            'bicicleta': 'bicicleta',
            'telefone': 'teléfono',
            'computador': 'computadora',
            'internet': 'internet',
            'email': 'email',
            'carta': 'carta',
            'jornal': 'periódico',
            'revista': 'revista',
            'televisão': 'televisión',
            'rádio': 'radio',
            'roupa': 'ropa',
            'camisa': 'camisa',
            'calça': 'pantalón',
            'vestido': 'vestido',
            'sapato': 'zapato',
            'chapéu': 'sombrero',
            'óculos': 'gafas',
            'relógio': 'reloj',
            'bolsa': 'bolsa',
            'mala': 'maleta',
            'presente': 'regalo',
            'festa': 'fiesta',
            'casamento': 'boda',
            'aniversário': 'cumpleaños',
            'natal': 'navidad',
            'ano novo': 'año nuevo',
            'férias': 'vacaciones',
            'viagem': 'viaje',
            'hotel': 'hotel',
            'restaurante': 'restaurante',
            'loja': 'tienda',
            'mercado': 'mercado',
            'banco': 'banco',
            'hospital': 'hospital',
            'médico': 'médico',
            'enfermeiro': 'enfermero',
            'remédio': 'medicina',
            'doença': 'enfermedad',
            'saúde': 'salud',
            'corpo': 'cuerpo',
            'cabeça': 'cabeza',
            'olho': 'ojo',
            'orelha': 'oreja',
            'nariz': 'nariz',
            'boca': 'boca',
            'dente': 'diente',
            'pescoço': 'cuello',
            'braço': 'brazo',
            'mão': 'mano',
            'dedo': 'dedo',
            'peito': 'pecho',
            'costas': 'espalda',
            'barriga': 'barriga',
            'perna': 'pierna',
            'pé': 'pie',
            'coração': 'corazón',
            'sangue': 'sangre',
            'osso': 'hueso',
            'pele': 'piel',
            'cabelo': 'cabello',
            'animal': 'animal',
            'cachorro': 'perro',
            'gato': 'gato',
            'pássaro': 'pájaro',
            'peixe': 'pez',
            'cavalo': 'caballo',
            'vaca': 'vaca',
            'porco': 'cerdo',
            'galinha': 'gallina',
            'árvore': 'árbol',
            'flor': 'flor',
            'planta': 'planta',
            'folha': 'hoja',
            'fruto': 'fruto',
            'semente': 'semilla',
            'raiz': 'raíz',
            'madeira': 'madera',
            'pedra': 'piedra',
            'metal': 'metal',
            'ouro': 'oro',
            'prata': 'plata',
            'ferro': 'hierro',
            'vidro': 'vidrio',
            'papel': 'papel',
            'plástico': 'plástico',
            'tecido': 'tela',
            'algodão': 'algodón',
            'lã': 'lana',
            'seda': 'seda',
            'couro': 'cuero',
            'borracha': 'goma',
            'óleo': 'aceite',
            'gasolina': 'gasolina',
            'eletricidade': 'electricidad',
            'energia': 'energía',
            'força': 'fuerza',
            'velocidade': 'velocidad',
            'distância': 'distancia',
            'peso': 'peso',
            'tamanho': 'tamaño',
            'altura': 'altura',
            'largura': 'anchura',
            'comprimento': 'longitud',
            'profundidade': 'profundidad',
            'temperatura': 'temperatura',
            'calor': 'calor',
            'frio': 'frío',
            'gelo': 'hielo',
            'vapor': 'vapor',
            'fumaça': 'humo',
            'cheiro': 'olor',
            'som': 'sonido',
            'ruído': 'ruido',
            'silêncio': 'silencio',
            'voz': 'voz',
            'grito': 'grito',
            'riso': 'risa',
            'choro': 'llanto',
            'sorriso': 'sonrisa',
            'lágrima': 'lágrima',
            'alegria': 'alegría',
            'tristeza': 'tristeza',
            'raiva': 'ira',
            'medo': 'miedo',
            'amor': 'amor',
            'ódio': 'odio',
            'paz': 'paz',
            'guerra': 'guerra',
            'luta': 'lucha',
            'vitória': 'victoria',
            'derrota': 'derrota',
            'sucesso': 'éxito',
            'fracasso': 'fracaso',
            'sorte': 'suerte',
            'azar': 'mala suerte',
            'problema': 'problema',
            'solução': 'solución',
            'pergunta': 'pregunta',
            'resposta': 'respuesta',
            'verdade': 'verdad',
            'mentira': 'mentira',
            'segredo': 'secreto',
            'informação': 'información',
            'conhecimento': 'conocimiento',
            'sabedoria': 'sabiduría',
            'inteligência': 'inteligencia',
            'memória': 'memoria',
            'sonho': 'sueño',
            'realidade': 'realidad',
            'fantasia': 'fantasía',
            'imaginação': 'imaginación',
            'criatividade': 'creatividad',
            'arte': 'arte',
            'beleza': 'belleza',
            'feiura': 'fealdad',
            'cultura': 'cultura',
            'tradição': 'tradición',
            'costume': 'costumbre',
            'religião': 'religión',
            'deus': 'dios',
            'igreja': 'iglesia',
            'oração': 'oración',
            'fé': 'fe',
            'esperança': 'esperanza',
            'caridade': 'caridad',
            'bondade': 'bondad',
            'maldade': 'maldad',
            'justiça': 'justicia',
            'injustiça': 'injusticia',
            'lei': 'ley',
            'direito': 'derecho',
            'dever': 'deber',
            'responsabilidade': 'responsabilidad',
            'liberdade': 'libertad',
            'prisão': 'prisión',
            'governo': 'gobierno',
            'presidente': 'presidente',
            'ministro': 'ministro',
            'deputado': 'diputado',
            'senador': 'senador',
            'prefeito': 'alcalde',
            'vereador': 'concejal',
            'eleição': 'elección',
            'voto': 'voto',
            'democracia': 'democracia',
            'ditadura': 'dictadura',
            'república': 'república',
            'monarquia': 'monarquía',
            'império': 'imperio',
            'reino': 'reino',
            'nação': 'nación',
            'estado': 'estado',
            'província': 'provincia',
            'região': 'región',
            'continente': 'continente',
            'oceano': 'océano',
            'mar': 'mar',
            'rio': 'río',
            'lago': 'lago',
            'montanha': 'montaña',
            'vale': 'valle',
            'floresta': 'bosque',
            'deserto': 'desierto',
            'praia': 'playa',
            'ilha': 'isla',
            'ponte': 'puente',
            'estrada': 'carretera',
            'caminho': 'camino',
            'trilha': 'sendero',
            'porto': 'puerto',
            'aeroporto': 'aeropuerto',
            'estação': 'estación',
            'parada': 'parada',
            'semáforo': 'semáforo',
            'placa': 'placa',
            'sinal': 'señal',
            'mapa': 'mapa',
            'direção': 'dirección',
            'norte': 'norte',
            'sul': 'sur',
            'leste': 'este',
            'oeste': 'oeste',
            'centro': 'centro',
            'lado': 'lado',
            'frente': 'frente',
            'atrás': 'atrás',
            'cima': 'arriba',
            'baixo': 'abajo',
            'dentro': 'dentro',
            'fora': 'fuera',
            'perto': 'cerca',
            'longe': 'lejos',
            'aqui': 'aquí',
            'ali': 'allí',
            'lá': 'allá',
            'onde': 'dónde',
            'quando': 'cuándo',
            'como': 'cómo',
            'por que': 'por qué',
            'porque': 'porque',
            'quem': 'quién',
            'qual': 'cuál',
            'quanto': 'cuánto',
            'quantos': 'cuántos',
            'quantas': 'cuántas',
            'algum': 'algún',
            'alguma': 'alguna',
            'alguns': 'algunos',
            'algumas': 'algunas',
            'nenhum': 'ningún',
            'nenhuma': 'ninguna',
            'nenhuns': 'ningunos',
            'nenhumas': 'ningunas',
            'qualquer': 'cualquier',
            'quaisquer': 'cualesquiera',
            'sempre': 'siempre',
            'nunca': 'nunca',
            'às vezes': 'a veces',
            'frequentemente': 'frecuentemente',
            'raramente': 'raramente',
            'já': 'ya',
            'ainda': 'aún',
            'agora': 'ahora',
            'hoje': 'hoy',
            'ontem': 'ayer',
            'amanhã': 'mañana',
            'cedo': 'temprano',
            'tarde': 'tarde',
            'rápido': 'rápido',
            'devagar': 'despacio',
            'fácil': 'fácil',
            'difícil': 'difícil',
            'simples': 'simple',
            'complicado': 'complicado',
            'importante': 'importante',
            'necessário': 'necesario',
            'útil': 'útil',
            'inútil': 'inútil',
            'possível': 'posible',
            'impossível': 'imposible',
            'provável': 'probable',
            'improvável': 'improbable',
            'certo': 'cierto',
            'errado': 'equivocado',
            'correto': 'correcto',
            'incorreto': 'incorrecto',
            'verdadeiro': 'verdadero',
            'falso': 'falso',
            'real': 'real',
            'irreal': 'irreal',
            'natural': 'natural',
            'artificial': 'artificial',
            'normal': 'normal',
            'anormal': 'anormal',
            'comum': 'común',
            'raro': 'raro',
            'especial': 'especial',
            'geral': 'general',
            'particular': 'particular',
            'público': 'público',
            'privado': 'privado',
            'pessoal': 'personal',
            'social': 'social',
            'individual': 'individual',
            'coletivo': 'colectivo',
            'nacional': 'nacional',
            'internacional': 'internacional',
            'local': 'local',
            'regional': 'regional',
            'global': 'global',
            'mundial': 'mundial',
            'universal': 'universal',
            'total': 'total',
            'parcial': 'parcial',
            'completo': 'completo',
            'incompleto': 'incompleto',
            'cheio': 'lleno',
            'vazio': 'vacío',
            'aberto': 'abierto',
            'fechado': 'cerrado',
            'livre': 'libre',
            'ocupado': 'ocupado',
            'disponível': 'disponible',
            'indisponível': 'no disponible',
            'presente': 'presente',
            'ausente': 'ausente',
            'ativo': 'activo',
            'inativo': 'inactivo',
            'vivo': 'vivo',
            'morto': 'muerto',
            'jovem': 'joven',
            'velho': 'viejo',
            'novo': 'nuevo',
            'antigo': 'antiguo',
            'moderno': 'moderno',
            'tradicional': 'tradicional',
            'atual': 'actual',
            'passado': 'pasado',
            'futuro': 'futuro',
            'presente': 'presente',
            'anterior': 'anterior',
            'posterior': 'posterior',
            'próximo': 'próximo',
            'distante': 'distante',
            'recente': 'reciente',
            'antigo': 'antiguo',
            'original': 'original',
            'cópia': 'copia',
            'único': 'único',
            'múltiplo': 'múltiple',
            'single': 'soltero',
            'casado': 'casado',
            'divorciado': 'divorciado',
            'viúvo': 'viudo',
            'solteiro': 'soltero',
            'namorado': 'novio',
            'namorada': 'novia',
            'noivo': 'novio',
            'noiva': 'novia',
            'marido': 'marido',
            'esposa': 'esposa',
            'ex-marido': 'ex-marido',
            'ex-esposa': 'ex-esposa',
            'sogro': 'suegro',
            'sogra': 'suegra',
            'genro': 'yerno',
            'nora': 'nuera',
            'cunhado': 'cuñado',
            'cunhada': 'cuñada',
            'padrinho': 'padrino',
            'madrinha': 'madrina',
            'afilhado': 'ahijado',
            'afilhada': 'ahijada',
            'vizinho': 'vecino',
            'vizinha': 'vecina',
            'colega': 'colega',
            'companheiro': 'compañero',
            'companheira': 'compañera',
            'parceiro': 'socio',
            'parceira': 'socia',
            'chefe': 'jefe',
            'subordinado': 'subordinado',
            'funcionário': 'empleado',
            'empregado': 'empleado',
            'patrão': 'patrón',
            'cliente': 'cliente',
            'vendedor': 'vendedor',
            'comprador': 'comprador',
            'professor': 'profesor',
            'aluno': 'alumno',
            'estudante': 'estudiante',
            'diretor': 'director',
            'secretário': 'secretario',
            'advogado': 'abogado',
            'juiz': 'juez',
            'policial': 'policía',
            'bombeiro': 'bombero',
            'soldado': 'soldado',
            'engenheiro': 'ingeniero',
            'arquiteto': 'arquitecto',
            'dentista': 'dentista',
            'veterinário': 'veterinario',
            'farmacêutico': 'farmacéutico',
            'enfermeiro': 'enfermero',
            'psicólogo': 'psicólogo',
            'psiquiatra': 'psiquiatra',
            'terapeuta': 'terapeuta',
            'fisioterapeuta': 'fisioterapeuta',
            'nutricionista': 'nutricionista',
            'cozinheiro': 'cocinero',
            'garçom': 'camarero',
            'motorista': 'conductor',
            'piloto': 'piloto',
            'marinheiro': 'marinero',
            'pescador': 'pescador',
            'agricultor': 'agricultor',
            'jardineiro': 'jardinero',
            'pedreiro': 'albañil',
            'carpinteiro': 'carpintero',
            'eletricista': 'electricista',
            'encanador': 'fontanero',
            'pintor': 'pintor',
            'mecânico': 'mecánico',
            'técnico': 'técnico',
            'programador': 'programador',
            'designer': 'diseñador',
            'artista': 'artista',
            'músico': 'músico',
            'cantor': 'cantante',
            'ator': 'actor',
            'atriz': 'actriz',
            'diretor': 'director',
            'produtor': 'productor',
            'escritor': 'escritor',
            'jornalista': 'periodista',
            'fotógrafo': 'fotógrafo',
            'tradutor': 'traductor',
            'intérprete': 'intérprete',
            'guia': 'guía',
            'recepcionista': 'recepcionista',
            'segurança': 'seguridad',
            'limpeza': 'limpieza',
            'faxineiro': 'limpiador',
            'porteiro': 'portero',
            'zelador': 'conserje',
            'administrador': 'administrador',
            'gerente': 'gerente',
            'supervisor': 'supervisor',
            'coordenador': 'coordinador',
            'assistente': 'asistente',
            'secretária': 'secretaria',
            'recepcionista': 'recepcionista',
            'telefonista': 'telefonista',
            'operador': 'operador',
            'atendente': 'atendiente',
            'vendedor': 'vendedor',
            'representante': 'representante',
            'consultor': 'consultor',
            'analista': 'analista',
            'especialista': 'especialista',
            'expert': 'experto',
            'profissional': 'profesional',
            'amador': 'amateur',
            'voluntário': 'voluntario',
            'estagiário': 'becario',
            'aprendiz': 'aprendiz',
            'trainee': 'trainee',
            'júnior': 'junior',
            'sênior': 'senior',
            'pleno': 'pleno',
            'iniciante': 'principiante',
            'experiente': 'experimentado',
            'qualificado': 'cualificado',
            'capacitado': 'capacitado',
            'treinado': 'entrenado',
            'formado': 'graduado',
            'graduado': 'graduado',
            'pós-graduado': 'postgraduado',
            'mestre': 'maestro',
            'doutor': 'doctor',
            'PhD': 'PhD',
            'bacharel': 'licenciado',
            'técnico': 'técnico',
            'tecnólogo': 'tecnólogo',
            'curso': 'curso',
            'disciplina': 'asignatura',
            'matéria': 'materia',
            'aula': 'clase',
            'lição': 'lección',
            'exercício': 'ejercicio',
            'tarefa': 'tarea',
            'dever de casa': 'deberes',
            'prova': 'examen',
            'teste': 'prueba',
            'avaliação': 'evaluación',
            'nota': 'nota',
            'conceito': 'concepto',
            'aprovado': 'aprobado',
            'reprovado': 'reprobado',
            'recuperação': 'recuperación',
            'dependência': 'dependencia',
            'diploma': 'diploma',
            'certificado': 'certificado',
            'título': 'título',
            'grau': 'grado',
            'nível': 'nivel',
            'série': 'serie',
            'ano': 'año',
            'semestre': 'semestre',
            'trimestre': 'trimestre',
            'bimestre': 'bimestre',
            'período': 'período',
            'etapa': 'etapa',
            'fase': 'fase',
            'ciclo': 'ciclo',
            'turma': 'grupo',
            'classe': 'clase',
            'sala de aula': 'aula',
            'laboratório': 'laboratorio',
            'biblioteca': 'biblioteca',
            'cantina': 'cantina',
            'refeitório': 'comedor',
            'pátio': 'patio',
            'quadra': 'cancha',
            'ginásio': 'gimnasio',
            'piscina': 'piscina',
            'auditório': 'auditorio',
            'teatro': 'teatro',
            'cinema': 'cine',
            'museu': 'museo',
            'galeria': 'galería',
            'exposição': 'exposición',
            'feira': 'feria',
            'mercado': 'mercado',
            'shopping': 'centro comercial',
            'loja': 'tienda',
            'boutique': 'boutique',
            'farmácia': 'farmacia',
            'padaria': 'panadería',
            'açougue': 'carnicería',
            'peixaria': 'pescadería',
            'frutaria': 'frutería',
            'verduraria': 'verdulería',
            'floricultura': 'floristería',
            'livraria': 'librería',
            'papelaria': 'papelería',
            'banca de jornal': 'quiosco',
            'posto de gasolina': 'gasolinera',
            'oficina': 'taller',
            'garagem': 'garaje',
            'estacionamento': 'aparcamiento',
            'parque': 'parque',
            'praça': 'plaza',
            'jardim': 'jardín',
            'zoológico': 'zoológico',
            'aquário': 'acuario',
            'circo': 'circo',
            'parque de diversões': 'parque de atracciones',
            'praia': 'playa',
            'piscina': 'piscina',
            'clube': 'club',
            'academia': 'gimnasio',
            'spa': 'spa',
            'salão de beleza': 'salón de belleza',
            'barbearia': 'barbería',
            'clínica': 'clínica',
            'consultório': 'consultorio',
            'laboratório': 'laboratorio',
            'farmácia': 'farmacia',
            'pronto-socorro': 'urgencias',
            'ambulância': 'ambulancia',
            'bombeiros': 'bomberos',
            'polícia': 'policía',
            'delegacia': 'comisaría',
            'tribunal': 'tribunal',
            'fórum': 'juzgado',
            'cartório': 'notaría',
            'prefeitura': 'ayuntamiento',
            'câmara': 'cámara',
            'assembleia': 'asamblea',
            'congresso': 'congreso',
            'senado': 'senado',
            'ministério': 'ministerio',
            'secretaria': 'secretaría',
            'departamento': 'departamento',
            'seção': 'sección',
            'divisão': 'división',
            'setor': 'sector',
            'área': 'área',
            'zona': 'zona',
            'região': 'región',
            'território': 'territorio',
            'distrito': 'distrito',
            'bairro': 'barrio',
            'vizinhança': 'vecindario',
            'comunidade': 'comunidad',
            'sociedade': 'sociedad',
            'grupo': 'grupo',
            'equipe': 'equipo',
            'time': 'equipo',
            'clube': 'club',
            'associação': 'asociación',
            'organização': 'organización',
            'instituição': 'institución',
            'empresa': 'empresa',
            'firma': 'firma',
            'corporação': 'corporación',
            'companhia': 'compañía',
            'negócio': 'negocio',
            'comércio': 'comercio',
            'indústria': 'industria',
            'fábrica': 'fábrica',
            'usina': 'central',
            'refinaria': 'refinería',
            'mina': 'mina',
            'fazenda': 'granja',
            'sítio': 'finca',
            'chácara': 'chacra',
            'rancho': 'rancho',
            'estância': 'estancia',
            'hacienda': 'hacienda',
            'plantação': 'plantación',
            'cultivo': 'cultivo',
            'colheita': 'cosecha',
            'safra': 'cosecha',
            'produção': 'producción',
            'fabricação': 'fabricación',
            'manufatura': 'manufactura',
            'montagem': 'montaje',
            'construção': 'construcción',
            'obra': 'obra',
            'projeto': 'proyecto',
            'plano': 'plan',
            'programa': 'programa',
            'sistema': 'sistema',
            'método': 'método',
            'processo': 'proceso',
            'procedimento': 'procedimiento',
            'técnica': 'técnica',
            'estratégia': 'estrategia',
            'tática': 'táctica',
            'abordagem': 'enfoque',
            'aproximação': 'aproximación',
            'caminho': 'camino',
            'via': 'vía',
            'meio': 'medio',
            'forma': 'forma',
            'maneira': 'manera',
            'modo': 'modo',
            'jeito': 'manera',
            'estilo': 'estilo',
            'tipo': 'tipo',
            'espécie': 'especie',
            'categoria': 'categoría',
            'classe': 'clase',
            'grupo': 'grupo',
            'conjunto': 'conjunto',
            'coleção': 'colección',
            'série': 'serie',
            'sequência': 'secuencia',
            'ordem': 'orden',
            'organização': 'organización',
            'estrutura': 'estructura',
            'formato': 'formato',
            'design': 'diseño',
            'modelo': 'modelo',
            'padrão': 'patrón',
            'exemplo': 'ejemplo',
            'amostra': 'muestra',
            'caso': 'caso',
            'situação': 'situación',
            'condição': 'condición',
            'estado': 'estado',
            'posição': 'posición',
            'lugar': 'lugar',
            'local': 'local',
            'localização': 'ubicación',
            'endereço': 'dirección',
            'coordenada': 'coordenada',
            'ponto': 'punto',
            'marca': 'marca',
            'sinal': 'señal',
            'símbolo': 'símbolo',
            'ícone': 'icono',
            'imagem': 'imagen',
            'figura': 'figura',
            'desenho': 'dibujo',
            'ilustração': 'ilustración',
            'gráfico': 'gráfico',
            'diagrama': 'diagrama',
            'esquema': 'esquema',
            'mapa': 'mapa',
            'planta': 'plano',
            'layout': 'diseño',
            'arranjo': 'arreglo',
            'disposição': 'disposición',
            'configuração': 'configuración',
            'ajuste': 'ajuste',
            'regulagem': 'regulación',
            'controle': 'control',
            'comando': 'comando',
            'instrução': 'instrucción',
            'orientação': 'orientación',
            'direção': 'dirección',
            'guia': 'guía',
            'manual': 'manual',
            'tutorial': 'tutorial',
            'curso': 'curso',
            'treinamento': 'entrenamiento',
            'capacitação': 'capacitación',
            'qualificação': 'cualificación',
            'especialização': 'especialización',
            'aperfeiçoamento': 'perfeccionamiento',
            'desenvolvimento': 'desarrollo',
            'crescimento': 'crecimiento',
            'evolução': 'evolución',
            'progresso': 'progreso',
            'avanço': 'avance',
            'melhoria': 'mejora',
            'aprimoramento': 'mejoramiento',
            'otimização': 'optimización',
            'maximização': 'maximización',
            'minimização': 'minimización',
            'redução': 'reducción',
            'diminuição': 'disminución',
            'aumento': 'aumento',
            'incremento': 'incremento',
            'acréscimo': 'aumento',
            'adição': 'adición',
            'soma': 'suma',
            'subtração': 'sustracción',
            'multiplicação': 'multiplicación',
            'divisão': 'división',
            'cálculo': 'cálculo',
            'conta': 'cuenta',
            'operação': 'operación',
            'função': 'función',
            'fórmula': 'fórmula',
            'equação': 'ecuación',
            'resultado': 'resultado',
            'resposta': 'respuesta',
            'solução': 'solución',
            'resolução': 'resolución',
            'conclusão': 'conclusión',
            'fim': 'fin',
            'final': 'final',
            'término': 'término',
            'encerramento': 'cierre',
            'fechamento': 'cierre',
            'abertura': 'apertura',
            'início': 'inicio',
            'começo': 'comienzo',
            'princípio': 'principio',
            'origem': 'origen',
            'fonte': 'fuente',
            'base': 'base',
            'fundamento': 'fundamento',
            'alicerce': 'cimiento',
            'estrutura': 'estructura',
            'esqueleto': 'esqueleto',
            'armação': 'armazón',
            'moldura': 'marco',
            'quadro': 'cuadro',
            'tela': 'lienzo',
            'pintura': 'pintura',
            'retrato': 'retrato',
            'paisagem': 'paisaje',
            'natureza': 'naturaleza',
            'ambiente': 'ambiente',
            'meio ambiente': 'medio ambiente',
            'ecologia': 'ecología',
            'sustentabilidade': 'sostenibilidad',
            'preservação': 'preservación',
            'conservação': 'conservación',
            'proteção': 'protección',
            'defesa': 'defensa',
            'segurança': 'seguridad',
            'proteção': 'protección',
            'cuidado': 'cuidado',
            'atenção': 'atención',
            'concentração': 'concentración',
            'foco': 'foco',
            'objetivo': 'objetivo',
            'meta': 'meta',
            'alvo': 'objetivo',
            'propósito': 'propósito',
            'intenção': 'intención',
            'vontade': 'voluntad',
            'desejo': 'deseo',
            'sonho': 'sueño',
            'ambição': 'ambición',
            'aspiração': 'aspiración',
            'esperança': 'esperanza',
            'expectativa': 'expectativa',
            'previsão': 'previsión',
            'predição': 'predicción',
            'profecia': 'profecía',
            'adivinhação': 'adivinación',
            'suposição': 'suposición',
            'hipótese': 'hipótesis',
            'teoria': 'teoría',
            'conceito': 'concepto',
            'ideia': 'idea',
            'pensamento': 'pensamiento',
            'opinião': 'opinión',
            'ponto de vista': 'punto de vista',
            'perspectiva': 'perspectiva',
            'visão': 'visión',
            'olhar': 'mirada',
            'observação': 'observación',
            'percepção': 'percepción',
            'sensação': 'sensación',
            'sentimento': 'sentimiento',
            'emoção': 'emoción',
            'paixão': 'pasión',
            'entusiasmo': 'entusiasmo',
            'animação': 'animación',
            'excitação': 'excitación',
            'agitação': 'agitación',
            'nervosismo': 'nerviosismo',
            'ansiedade': 'ansiedad',
            'preocupação': 'preocupación',
            'inquietação': 'inquietud',
            'tranquilidade': 'tranquilidad',
            'calma': 'calma',
            'serenidade': 'serenidad',
            'paz': 'paz',
            'harmonia': 'armonía',
            'equilíbrio': 'equilibrio',
            'estabilidade': 'estabilidad',
            'segurança': 'seguridad',
            'confiança': 'confianza',
            'certeza': 'certeza',
            'garantia': 'garantía',
            'promessa': 'promesa',
            'compromisso': 'compromiso',
            'acordo': 'acuerdo',
            'contrato': 'contrato',
            'negociação': 'negociación',
            'discussão': 'discusión',
            'debate': 'debate',
            'conversa': 'conversación',
            'diálogo': 'diálogo',
            'comunicação': 'comunicación',
            'mensagem': 'mensaje',
            'recado': 'recado',
            'aviso': 'aviso',
            'notícia': 'noticia',
            'informação': 'información',
            'dado': 'dato',
            'fato': 'hecho',
            'evento': 'evento',
            'acontecimento': 'acontecimiento',
            'ocorrência': 'ocurrencia',
            'incidente': 'incidente',
            'acidente': 'accidente',
            'emergência': 'emergencia',
            'urgência': 'urgencia',
            'pressa': 'prisa',
            'rapidez': 'rapidez',
            'velocidade': 'velocidad',
            'lentidão': 'lentitud',
            'demora': 'demora',
            'atraso': 'retraso',
            'pontualidade': 'puntualidad',
            'horário': 'horario',
            'agenda': 'agenda',
            'cronograma': 'cronograma',
            'calendário': 'calendario',
            'data': 'fecha',
            'prazo': 'plazo',
            'limite': 'límite',
            'fronteira': 'frontera',
            'divisa': 'frontera',
            'linha': 'línea',
            'borda': 'borde',
            'margem': 'margen',
            'extremidade': 'extremidad',
            'ponta': 'punta',
            'fim': 'fin',
            'cabo': 'cabo',
            'rabo': 'cola',
            'cauda': 'cola',
            'traseiro': 'trasero',
            'parte de trás': 'parte trasera',
            'costas': 'espalda',
            'dorso': 'dorso',
            'verso': 'reverso',
            'avesso': 'revés',
            'interior': 'interior',
            'dentro': 'dentro',
            'interno': 'interno',
            'íntimo': 'íntimo',
            'privado': 'privado',
            'secreto': 'secreto',
            'confidencial': 'confidencial',
            'reservado': 'reservado',
            'exclusivo': 'exclusivo',
            'especial': 'especial',
            'particular': 'particular',
            'individual': 'individual',
            'pessoal': 'personal',
            'próprio': 'propio',
            'seu': 'su',
            'sua': 'su',
            'seus': 'sus',
            'suas': 'sus',
            'meu': 'mi',
            'minha': 'mi',
            'meus': 'mis',
            'minhas': 'mis',
            'nosso': 'nuestro',
            'nossa': 'nuestra',
            'nossos': 'nuestros',
            'nossas': 'nuestras',
            'vosso': 'vuestro',
            'vossa': 'vuestra',
            'vossos': 'vuestros',
            'vossas': 'vuestras',
            'dele': 'de él',
            'dela': 'de ella',
            'deles': 'de ellos',
            'delas': 'de ellas',
            'eu': 'yo',
            'tu': 'tú',
            'você': 'usted',
            'ele': 'él',
            'ela': 'ella',
            'nós': 'nosotros',
            'vós': 'vosotros',
            'vocês': 'ustedes',
            'eles': 'ellos',
            'elas': 'ellas',
            'me': 'me',
            'te': 'te',
            'se': 'se',
            'nos': 'nos',
            'vos': 'os',
            'lhe': 'le',
            'lhes': 'les',
            'o': 'lo',
            'a': 'la',
            'os': 'los',
            'as': 'las',
            'este': 'este',
            'esta': 'esta',
            'estes': 'estos',
            'estas': 'estas',
            'esse': 'ese',
            'essa': 'esa',
            'esses': 'esos',
            'essas': 'esas',
            'aquele': 'aquel',
            'aquela': 'aquella',
            'aqueles': 'aquellos',
            'aquelas': 'aquellas',
            'isto': 'esto',
            'isso': 'eso',
            'aquilo': 'aquello',
            'aqui': 'aquí',
            'aí': 'ahí',
            'ali': 'allí',
            'lá': 'allá',
            'cá': 'acá',
            'onde': 'dónde',
            'aonde': 'adónde',
            'donde': 'donde',
            'quando': 'cuándo',
            'como': 'cómo',
            'por que': 'por qué',
            'porque': 'porque',
            'para que': 'para qué',
            'quem': 'quién',
            'qual': 'cuál',
            'quanto': 'cuánto',
            'quantos': 'cuántos',
            'quantas': 'cuántas',
            'que': 'qué',
            'o que': 'qué',
            'o quê': 'qué',
            'sim': 'sí',
            'não': 'no',
            'talvez': 'tal vez',
            'quiçá': 'quizás',
            'possivelmente': 'posiblemente',
            'provavelmente': 'probablemente',
            'certamente': 'ciertamente',
            'definitivamente': 'definitivamente',
            'absolutamente': 'absolutamente',
            'completamente': 'completamente',
            'totalmente': 'totalmente',
            'inteiramente': 'enteramente',
            'parcialmente': 'parcialmente',
            'principalmente': 'principalmente',
            'especialmente': 'especialmente',
            'particularmente': 'particularmente',
            'geralmente': 'generalmente',
            'normalmente': 'normalmente',
            'habitualmente': 'habitualmente',
            'frequentemente': 'frecuentemente',
            'constantemente': 'constantemente',
            'continuamente': 'continuamente',
            'permanentemente': 'permanentemente',
            'temporariamente': 'temporalmente',
            'momentaneamente': 'momentáneamente',
            'instantaneamente': 'instantáneamente',
            'imediatamente': 'inmediatamente',
            'rapidamente': 'rápidamente',
            'lentamente': 'lentamente',
            'devagar': 'despacio',
            'depressa': 'deprisa',
            'cuidadosamente': 'cuidadosamente',
            'atentamente': 'atentamente',
            'silenciosamente': 'silenciosamente',
            'calmamente': 'calmamente',
            'tranquilamente': 'tranquilamente',
            'nervosamente': 'nerviosamente',
            'ansiosamente': 'ansiosamente',
            'alegremente': 'alegremente',
            'tristemente': 'tristemente',
            'felizmente': 'felizmente',
            'infelizmente': 'infelizmente',
            'sorte': 'suerte',
            'azar': 'mala suerte',
            'feliz': 'feliz',
            'triste': 'triste',
            'alegre': 'alegre',
            'contente': 'contento',
            'satisfeito': 'satisfecho',
            'insatisfeito': 'insatisfecho',
            'preocupado': 'preocupado',
            'tranquilo': 'tranquilo',
            'calmo': 'calmado',
            'nervoso': 'nervioso',
            'ansioso': 'ansioso',
            'estressado': 'estresado',
            'relaxado': 'relajado',
            'cansado': 'cansado',
            'descansado': 'descansado',
            'acordado': 'despierto',
            'dormindo': 'durmiendo',
            'sonolento': 'somnoliento',
            'desperto': 'despierto',
            'atento': 'atento',
            'distraído': 'distraído',
            'concentrado': 'concentrado',
            'focado': 'enfocado',
            'confuso': 'confuso',
            'perdido': 'perdido',
            'encontrado': 'encontrado',
            'achado': 'encontrado',
            'perdido': 'perdido',
            'sumido': 'desaparecido',
            'desaparecido': 'desaparecido',
            'presente': 'presente',
            'ausente': 'ausente',
            'aqui': 'aquí',
            'ali': 'allí',
            'lá': 'allá',
            'longe': 'lejos',
            'perto': 'cerca',
            'próximo': 'próximo',
            'distante': 'distante',
            'alto': 'alto',
            'baixo': 'bajo',
            'grande': 'grande',
            'pequeno': 'pequeño',
            'enorme': 'enorme',
            'gigante': 'gigante',
            'imenso': 'inmenso',
            'minúsculo': 'minúsculo',
            'tiny': 'diminuto',
            'largo': 'ancho',
            'estreito': 'estrecho',
            'fino': 'fino',
            'grosso': 'grueso',
            'espesso': 'espeso',
            'delgado': 'delgado',
            'magro': 'flaco',
            'gordo': 'gordo',
            'obeso': 'obeso',
            'forte': 'fuerte',
            'fraco': 'débil',
            'poderoso': 'poderoso',
            'potente': 'potente',
            'frágil': 'frágil',
            'resistente': 'resistente',
            'duro': 'duro',
            'mole': 'blando',
            'macio': 'suave',
            'áspero': 'áspero',
            'liso': 'liso',
            'rugoso': 'rugoso',
            'quente': 'caliente',
            'frio': 'frío',
            'morno': 'tibio',
            'gelado': 'helado',
            'congelado': 'congelado',
            'derretido': 'derretido',
            'líquido': 'líquido',
            'sólido': 'sólido',
            'gasoso': 'gaseoso',
            'molhado': 'mojado',
            'seco': 'seco',
            'úmido': 'húmedo',
            'encharcado': 'empapado',
            'limpo': 'limpio',
            'sujo': 'sucio',
            'puro': 'puro',
            'impuro': 'impuro',
            'claro': 'claro',
            'escuro': 'oscuro',
            'brilhante': 'brillante',
            'opaco': 'opaco',
            'transparente': 'transparente',
            'translúcido': 'translúcido',
            'colorido': 'colorido',
            'incolor': 'incoloro',
            'doce': 'dulce',
            'amargo': 'amargo',
            'azedo': 'agrio',
            'salgado': 'salado',
            'picante': 'picante',
            'temperado': 'condimentado',
            'sem sal': 'sin sal',
            'sem açúcar': 'sin azúcar',
            'diet': 'diet',
            'light': 'light',
            'natural': 'natural',
            'orgânico': 'orgánico',
            'artificial': 'artificial',
            'sintético': 'sintético',
            'químico': 'químico',
            'tóxico': 'tóxico',
            'venenoso': 'venenoso',
            'perigoso': 'peligroso',
            'seguro': 'seguro',
            'arriscado': 'arriesgado',
            'cauteloso': 'cauteloso',
            'cuidadoso': 'cuidadoso',
            'descuidado': 'descuidado',
            'negligente': 'negligente',
            'responsável': 'responsable',
            'irresponsável': 'irresponsable',
            'confiável': 'confiable',
            'inconfiável': 'no confiable',
            'honesto': 'honesto',
            'desonesto': 'deshonesto',
            'sincero': 'sincero',
            'falso': 'falso',
            'verdadeiro': 'verdadero',
            'mentiroso': 'mentiroso',
            'leal': 'leal',
            'desleal': 'desleal',
            'fiel': 'fiel',
            'infiel': 'infiel',
            'traidor': 'traidor',
            'corajoso': 'valiente',
            'medroso': 'miedoso',
            'bravo': 'bravo',
            'covarde': 'cobarde',
            'herói': 'héroe',
            'heroína': 'heroína',
            'vilão': 'villano',
            'bandido': 'bandido',
            'criminoso': 'criminal',
            'ladrão': 'ladrón',
            'assassino': 'asesino',
            'vítima': 'víctima',
            'inocente': 'inocente',
            'culpado': 'culpable',
            'justo': 'justo',
            'injusto': 'injusto',
            'correto': 'correcto',
            'incorreto': 'incorrecto',
            'certo': 'cierto',
            'errado': 'equivocado',
            'acertado': 'acertado',
            'equivocado': 'equivocado',
            'preciso': 'preciso',
            'impreciso': 'impreciso',
            'exato': 'exacto',
            'inexato': 'inexacto',
            'perfeito': 'perfecto',
            'imperfeito': 'imperfecto',
            'completo': 'completo',
            'incompleto': 'incompleto',
            'acabado': 'acabado',
            'inacabado': 'inacabado',
            'terminado': 'terminado',
            'interminado': 'interminable',
            'infinito': 'infinito',
            'finito': 'finito',
            'limitado': 'limitado',
            'ilimitado': 'ilimitado',
            'restrito': 'restringido',
            'irrestrito': 'sin restricciones',
            'livre': 'libre',
            'preso': 'preso',
            'solto': 'suelto',
            'amarrado': 'atado',
            'ligado': 'conectado',
            'desligado': 'desconectado',
            'conectado': 'conectado',
            'desconectado': 'desconectado',
            'unido': 'unido',
            'separado': 'separado',
            'junto': 'junto',
            'sozinho': 'solo',
            'acompanhado': 'acompañado',
            'isolado': 'aislado',
            'integrado': 'integrado',
            'incluído': 'incluido',
            'excluído': 'excluido',
            'aceito': 'aceptado',
            'rejeitado': 'rechazado',
            'aprovado': 'aprobado',
            'reprovado': 'reprobado',
            'permitido': 'permitido',
            'proibido': 'prohibido',
            'autorizado': 'autorizado',
            'não autorizado': 'no autorizado',
            'legal': 'legal',
            'ilegal': 'ilegal',
            'válido': 'válido',
            'inválido': 'inválido',
            'oficial': 'oficial',
            'não oficial': 'no oficial',
            'formal': 'formal',
            'informal': 'informal',
            'sério': 'serio',
            'brincalhão': 'juguetón',
            'divertido': 'divertido',
            'chato': 'aburrido',
            'interessante': 'interesante',
            'desinteressante': 'desinteresante',
            'emocionante': 'emocionante',
            'entediante': 'aburrido',
            'animado': 'animado',
            'desanimado': 'desanimado',
            'motivado': 'motivado',
            'desmotivado': 'desmotivado',
            'inspirado': 'inspirado',
            'criativo': 'creativo',
            'imaginativo': 'imaginativo',
            'original': 'original',
            'copiado': 'copiado',
            'imitado': 'imitado',
            'falso': 'falso',
            'autêntico': 'auténtico',
            'genuíno': 'genuino',
            'real': 'real',
            'irreal': 'irreal',
            'fantástico': 'fantástico',
            'incrível': 'increíble',
            'impressionante': 'impresionante',
            'surpreendente': 'sorprendente',
            'chocante': 'impactante',
            'normal': 'normal',
            'anormal': 'anormal',
            'estranho': 'extraño',
            'esquisito': 'raro',
            'bizarro': 'bizarro',
            'comum': 'común',
            'raro': 'raro',
            'único': 'único',
            'especial': 'especial',
            'extraordinário': 'extraordinario',
            'excepcional': 'excepcional',
            'notável': 'notable',
            'remarkável': 'notable',
            'memorável': 'memorable',
            'inesquecível': 'inolvidable',
            'esquecível': 'olvidable',
            'importante': 'importante',
            'insignificante': 'insignificante',
            'relevante': 'relevante',
            'irrelevante': 'irrelevante',
            'significativo': 'significativo',
            'insignificativo': 'insignificativo',
            'valioso': 'valioso',
            'sem valor': 'sin valor',
            'caro': 'caro',
            'barato': 'barato',
            'grátis': 'gratis',
            'gratuito': 'gratuito',
            'pago': 'pagado',
            'devido': 'debido',
            'em dívida': 'en deuda',
            'devedor': 'deudor',
            'credor': 'acreedor',
            'rico': 'rico',
            'pobre': 'pobre',
            'milionário': 'millonario',
            'bilionário': 'billonario',
            'endividado': 'endeudado',
            'falido': 'quebrado',
            'próspero': 'próspero',
            'bem-sucedido': 'exitoso',
            'fracassado': 'fracasado',
            'vencedor': 'ganador',
            'perdedor': 'perdedor',
            'campeão': 'campeón',
            'vice-campeão': 'subcampeón',
            'finalista': 'finalista',
            'semifinalista': 'semifinalista',
            'competidor': 'competidor',
            'rival': 'rival',
            'adversário': 'adversario',
            'inimigo': 'enemigo',
            'amigo': 'amigo',
            'aliado': 'aliado',
            'parceiro': 'socio',
            'sócio': 'socio',
            'colega': 'colega',
            'companheiro': 'compañero',
            'conhecido': 'conocido',
            'desconhecido': 'desconocido',
            'estranho': 'extraño',
            'familiar': 'familiar',
            'íntimo': 'íntimo',
            'próximo': 'cercano',
            'distante': 'distante',
            'relacionado': 'relacionado',
            'não relacionado': 'no relacionado',
            'conectado': 'conectado',
            'ligado': 'ligado',
            'vinculado': 'vinculado',
            'associado': 'asociado',
            'independente': 'independiente',
            'dependente': 'dependiente',
            'autônomo': 'autónomo',
            'livre': 'libre',
            'subordinado': 'subordinado',
            'superior': 'superior',
            'inferior': 'inferior',
            'igual': 'igual',
            'diferente': 'diferente',
            'similar': 'similar',
            'parecido': 'parecido',
            'idêntico': 'idéntico',
            'distinto': 'distinto',
            'oposto': 'opuesto',
            'contrário': 'contrario',
            'inverso': 'inverso',
            'reverso': 'reverso',
            'positivo': 'positivo',
            'negativo': 'negativo',
            'neutro': 'neutro',
            'favorável': 'favorable',
            'desfavorável': 'desfavorable',
            'vantajoso': 'ventajoso',
            'desvantajoso': 'desventajoso',
            'benéfico': 'beneficioso',
            'prejudicial': 'perjudicial',
            'útil': 'útil',
            'inútil': 'inútil',
            'eficaz': 'eficaz',
            'ineficaz': 'ineficaz',
            'eficiente': 'eficiente',
            'ineficiente': 'ineficiente',
            'produtivo': 'productivo',
            'improdutivo': 'improductivo',
            'lucrativo': 'lucrativo',
            'não lucrativo': 'sin fines de lucro',
            'rentável': 'rentable',
            'não rentável': 'no rentable',
            'viável': 'viable',
            'inviável': 'inviable',
            'factível': 'factible',
            'infactível': 'no factible',
            'realizável': 'realizable',
            'irrealizável': 'irrealizable',
            'alcançável': 'alcanzable',
            'inalcançável': 'inalcanzable',
            'acessível': 'accesible',
            'inacessível': 'inaccesible',
            'disponível': 'disponible',
            'indisponível': 'no disponible',
            'ocupado': 'ocupado',
            'livre': 'libre',
            'vago': 'vacante',
            'preenchido': 'ocupado',
            'cheio': 'lleno',
            'vazio': 'vacío',
            'lotado': 'lleno',
            'deserto': 'desierto',
            'povoado': 'poblado',
            'habitado': 'habitado',
            'desabitado': 'deshabitado',
            'civilizado': 'civilizado',
            'selvagem': 'salvaje',
            'doméstico': 'doméstico',
            'domesticado': 'domesticado',
            'manso': 'manso',
            'bravo': 'bravo',
            'feroz': 'feroz',
            'agressivo': 'agresivo',
            'pacífico': 'pacífico',
            'violento': 'violento',
            'calmo': 'calmado',
            'agitado': 'agitado',
            'quieto': 'quieto',
            'barulhento': 'ruidoso',
            'silencioso': 'silencioso',
            'mudo': 'mudo',
            'surdo': 'sordo',
            'cego': 'ciego',
            'deficiente': 'discapacitado',
            'saudável': 'saludable',
            'doente': 'enfermo',
            'são': 'sano',
            'insano': 'insano',
            'louco': 'loco',
            'maluco': 'loco',
            'normal': 'normal',
            'anormal': 'anormal',
            'estável': 'estable',
            'instável': 'inestable',
            'equilibrado': 'equilibrado',
            'desequilibrado': 'desequilibrado',
            'maduro': 'maduro',
            'imaturo': 'inmaduro',
            'adulto': 'adulto',
            'criança': 'niño',
            'bebê': 'bebé',
            'adolescente': 'adolescente',
            'jovem': 'joven',
            'idoso': 'anciano',
            'velho': 'viejo',
            'novo': 'nuevo',
            'recém-nascido': 'recién nacido',
            'nascido': 'nacido',
            'morto': 'muerto',
            'vivo': 'vivo',
            'existente': 'existente',
            'inexistente': 'inexistente',
            'presente': 'presente',
            'ausente': 'ausente',
            'atual': 'actual',
            'passado': 'pasado',
            'futuro': 'futuro',
            'antigo': 'antiguo',
            'moderno': 'moderno',
            'contemporâneo': 'contemporáneo',
            'histórico': 'histórico',
            'pré-histórico': 'prehistórico',
            'medieval': 'medieval',
            'clássico': 'clásico',
            'tradicional': 'tradicional',
            'inovador': 'innovador',
            'revolucionário': 'revolucionario',
            'conservador': 'conservador',
            'progressista': 'progresista',
            'liberal': 'liberal',
            'radical': 'radical',
            'moderado': 'moderado',
            'extremo': 'extremo',
            'central': 'central',
            'periférico': 'periférico',
            'marginal': 'marginal',
            'principal': 'principal',
            'secundário': 'secundario',
            'primário': 'primario',
            'terciário': 'terciario',
            'básico': 'básico',
            'avançado': 'avanzado',
            'elementar': 'elemental',
            'fundamental': 'fundamental',
            'essencial': 'esencial',
            'opcional': 'opcional',
            'obrigatório': 'obligatorio',
            'facultativo': 'facultativo',
            'voluntário': 'voluntario',
            'forçado': 'forzado',
            'espontâneo': 'espontáneo',
            'artificial': 'artificial',
            'natural': 'natural',
            'orgânico': 'orgánico',
            'inorgânico': 'inorgánico',
            'vivo': 'vivo',
            'morto': 'muerto',
            'animado': 'animado',
            'inanimado': 'inanimado',
            'consciente': 'consciente',
            'inconsciente': 'inconsciente',
            'desperto': 'despierto',
            'dormindo': 'durmiendo',
            'acordado': 'despierto',
            'sonhando': 'soñando',
            'pesadelo': 'pesadilla',
            'sonho': 'sueño',
            'realidade': 'realidad',
            'fantasia': 'fantasía',
            'ilusão': 'ilusión',
            'alucinação': 'alucinación',
            'visão': 'visión',
            'cegueira': 'ceguera',
            'audição': 'audición',
            'surdez': 'sordera',
            'fala': 'habla',
            'mudez': 'mudez',
            'tato': 'tacto',
            'olfato': 'olfato',
            'paladar': 'gusto',
            'sabor': 'sabor',
            'gosto': 'gusto',
            'cheiro': 'olor',
            'perfume': 'perfume',
            'fragrância': 'fragancia',
            'aroma': 'aroma',
            'fedor': 'hedor',
            'mau cheiro': 'mal olor',
            'bom cheiro': 'buen olor',
            'inodoro': 'inodoro',
            'perfumado': 'perfumado',
            'fedorento': 'maloliente',
            'aromático': 'aromático',
            'saboroso': 'sabroso',
            'sem sabor': 'sin sabor',
            'insípido': 'insípido',
            'temperado': 'condimentado',
            'sem tempero': 'sin condimento',
            'apimentado': 'picante',
            'suave': 'suave',
            'forte': 'fuerte',
            'fraco': 'débil',
            'intenso': 'intenso',
            'leve': 'leve',
            'pesado': 'pesado',
            'denso': 'denso',
            'ralo': 'ralo',
            'espesso': 'espeso',
            'fino': 'fino',
            'grosso': 'grueso',
            'largo': 'ancho',
            'estreito': 'estrecho',
            'comprido': 'largo',
            'curto': 'corto',
            'alto': 'alto',
            'baixo': 'bajo',
            'profundo': 'profundo',
            'raso': 'poco profundo',
            'superficial': 'superficial',
            'fundo': 'fondo',
            'superfície': 'superficie',
            'topo': 'cima',
            'base': 'base',
            'meio': 'medio',
            'centro': 'centro',
            'borda': 'borde',
            'margem': 'margen',
            'canto': 'esquina',
            'ângulo': 'ángulo',
            'curva': 'curva',
            'reta': 'recta',
            'linha': 'línea',
            'círculo': 'círculo',
            'quadrado': 'cuadrado',
            'retângulo': 'rectángulo',
            'triângulo': 'triángulo',
            'oval': 'óvalo',
            'redondo': 'redondo',
            'quadrado': 'cuadrado',
            'triangular': 'triangular',
            'circular': 'circular',
            'oval': 'ovalado',
            'retangular': 'rectangular',
            'geométrico': 'geométrico',
            'matemático': 'matemático',
            'científico': 'científico',
            'técnico': 'técnico',
            'prático': 'práctico',
            'teórico': 'teórico',
            'empírico': 'empírico',
            'experimental': 'experimental',
            'observacional': 'observacional',
            'analítico': 'analítico',
            'sintético': 'sintético',
            'lógico': 'lógico',
            'ilógico': 'ilógico',
            'racional': 'racional',
            'irracional': 'irracional',
            'sensato': 'sensato',
            'insensato': 'insensato',
            'razoável': 'razonable',
            'irrazoável': 'irrazonable',
            'coerente': 'coherente',
            'incoerente': 'incoherente',
            'consistente': 'consistente',
            'inconsistente': 'inconsistente',
            'contraditório': 'contradictorio',
            'paradoxal': 'paradójico',
            'absurdo': 'absurdo',
            'ridículo': 'ridículo',
            'engraçado': 'gracioso',
            'hilário': 'divertido',
            'cômico': 'cómico',
            'sério': 'serio',
            'solene': 'solemne',
            'formal': 'formal',
            'informal': 'informal',
            'casual': 'casual',
            'elegante': 'elegante',
            'sofisticado': 'sofisticado',
            'refinado': 'refinado',
            'grosseiro': 'grosero',
            'rude': 'rudo',
            'educado': 'educado',
            'mal-educado': 'maleducado',
            'cortês': 'cortés',
            'descortês': 'descortés',
            'gentil': 'gentil',
            'indelicado': 'indelicado',
            'amável': 'amable',
            'desagradável': 'desagradable',
            'simpático': 'simpático',
            'antipático': 'antipático',
            'agradável': 'agradable',
            'charmoso': 'encantador',
            'carismático': 'carismático',
            'atraente': 'atractivo',
            'repulsivo': 'repulsivo',
            'bonito': 'bonito',
            'feio': 'feo',
            'belo': 'hermoso',
            'lindo': 'lindo',
            'formoso': 'hermoso',
            'gracioso': 'gracioso',
            'elegante': 'elegante',
            'estiloso': 'con estilo',
            'na moda': 'de moda',
            'fora de moda': 'pasado de moda',
            'moderno': 'moderno',
            'antiquado': 'anticuado',
            'atual': 'actual',
            'desatualizado': 'desactualizado',
            'novo': 'nuevo',
            'usado': 'usado',
            'velho': 'viejo',
            'antigo': 'antiguo',
            'recente': 'reciente',
            'fresco': 'fresco',
            'estragado': 'estropeado',
            'podre': 'podrido',
            'deteriorado': 'deteriorado',
            'conservado': 'conservado',
            'preservado': 'preservado',
            'mantido': 'mantenido',
            'cuidado': 'cuidado',
            'negligenciado': 'descuidado',
            'abandonado': 'abandonado',
            'esquecido': 'olvidado',
            'lembrado': 'recordado',
            'memorizado': 'memorizado',
            'conhecido': 'conocido',
            'reconhecido': 'reconocido',
            'identificado': 'identificado',
            'anônimo': 'anónimo',
            'famoso': 'famoso',
            'célebre': 'célebre',
            'renomado': 'renombrado',
            'ilustre': 'ilustre',
            'notório': 'notorio',
            'obscuro': 'oscuro',
            'desconhecido': 'desconocido',
            'ignorado': 'ignorado',
            'popular': 'popular',
            'impopular': 'impopular',
            'querido': 'querido',
            'amado': 'amado',
            'adorado': 'adorado',
            'odiado': 'odiado',
            'desprezado': 'despreciado',
            'rejeitado': 'rechazado',
            'aceito': 'aceptado',
            'bem-vindo': 'bienvenido',
            'indesejado': 'no deseado',
            'desejado': 'deseado',
            'procurado': 'buscado',
            'perseguido': 'perseguido',
            'caçado': 'cazado',
            'fugitivo': 'fugitivo',
            'escondido': 'escondido',
            'perdido': 'perdido',
            'encontrado': 'encontrado',
            'achado': 'encontrado',
            'descoberto': 'descubierto',
            'revelado': 'revelado',
            'exposto': 'expuesto',
            'mostrado': 'mostrado',
            'exibido': 'exhibido',
            'demonstrado': 'demostrado',
            'provado': 'probado',
            'comprovado': 'comprobado',
            'confirmado': 'confirmado',
            'verificado': 'verificado',
            'checado': 'verificado',
            'testado': 'probado',
            'experimentado': 'experimentado',
            'tentado': 'intentado',
            'ensaiado': 'ensayado',
            'praticado': 'practicado',
            'treinado': 'entrenado',
            'exercitado': 'ejercitado',
            'preparado': 'preparado',
            'pronto': 'listo',
            'acabado': 'terminado',
            'finalizado': 'finalizado',
            'concluído': 'concluido',
            'terminado': 'terminado',
            'inacabado': 'inacabado',
            'incompleto': 'incompleto',
            'pendente': 'pendiente',
            'atrasado': 'atrasado',
            'adiantado': 'adelantado',
            'pontual': 'puntual',
            'no prazo': 'a tiempo',
            'fora do prazo': 'fuera de plazo',
            'vencido': 'vencido',
            'expirado': 'expirado',
            'válido': 'válido',
            'vigente': 'vigente',
            'ativo': 'activo',
            'inativo': 'inactivo',
            'funcionando': 'funcionando',
            'quebrado': 'roto',
            'estragado': 'estropeado',
            'danificado': 'dañado',
            'defeituoso': 'defectuoso',
            'perfeito': 'perfecto',
            'intacto': 'intacto',
            'íntegro': 'íntegro',
            'completo': 'completo',
            'total': 'total',
            'parcial': 'parcial',
            'metade': 'mitad',
            'meio': 'medio',
            'inteiro': 'entero',
            'todo': 'todo',
            'nada': 'nada',
            'algo': 'algo',
            'alguma coisa': 'algo',
            'qualquer coisa': 'cualquier cosa',
            'tudo': 'todo',
            'todos': 'todos',
            'ninguém': 'nadie',
            'alguém': 'alguien',
            'qualquer um': 'cualquiera',
            'cada um': 'cada uno',
            'ambos': 'ambos',
            'nenhum': 'ninguno',
            'vários': 'varios',
            'muitos': 'muchos',
            'poucos': 'pocos',
            'alguns': 'algunos',
            'bastante': 'bastante',
            'suficiente': 'suficiente',
            'insuficiente': 'insuficiente',
            'demais': 'demasiado',
            'excessivo': 'excesivo',
            'moderado': 'moderado',
            'equilibrado': 'equilibrado',
            'balanceado': 'balanceado',
            'proporcional': 'proporcional',
            'desproporcional': 'desproporcionado',
            'simétrico': 'simétrico',
            'assimétrico': 'asimétrico',
            'regular': 'regular',
            'irregular': 'irregular',
            'uniforme': 'uniforme',
            'desigual': 'desigual',
            'variado': 'variado',
            'diverso': 'diverso',
            'múltiplo': 'múltiple',
            'singular': 'singular',
            'plural': 'plural',
            'coletivo': 'colectivo',
            'individual': 'individual',
            'pessoal': 'personal',
            'privado': 'privado',
            'público': 'público',
            'comum': 'común',
            'compartilhado': 'compartido',
            'dividido': 'dividido',
            'separado': 'separado',
            'unido': 'unido',
            'conectado': 'conectado',
            'ligado': 'conectado',
            'relacionado': 'relacionado',
            'associado': 'asociado',
            'vinculado': 'vinculado',
            'independente': 'independiente',
            'autônomo': 'autónomo',
            'livre': 'libre',
            'solto': 'suelto',
            'preso': 'preso',
            'capturado': 'capturado',
            'libertado': 'liberado',
            'solto': 'liberado',
            'escapado': 'escapado',
            'fugido': 'huido',
            'perdido': 'perdido',
            'extraviado': 'extraviado',
            'sumido': 'desaparecido',
            'desaparecido': 'desaparecido',
            'ausente': 'ausente',
            'presente': 'presente',
            'aqui': 'aquí',
            'ali': 'allí',
            'lá': 'allá',
            'acolá': 'allá',
            'em algum lugar': 'en algún lugar',
            'em lugar nenhum': 'en ningún lugar',
            'em todo lugar': 'en todas partes',
            'por toda parte': 'por todas partes',
            'em qualquer lugar': 'en cualquier lugar',
            'onde quer que': 'dondequiera que',
            'aonde quer que': 'adondequiera que',
            'por onde': 'por donde',
            'de onde': 'de donde',
            'para onde': 'hacia donde',
            'até onde': 'hasta donde',
            'desde onde': 'desde donde'
        }
        
        # Padrões de tradução
        self.padroes_traducao = {
            # Terminações comuns
            r'ção$': 'ción',
            r'são$': 'sión',
            r'dade$': 'dad',
            r'mente$': 'mente',
            r'oso$': 'oso',
            r'osa$': 'osa',
            r'ivo$': 'ivo',
            r'iva$': 'iva',
            r'ado$': 'ado',
            r'ada$': 'ada',
            r'ido$': 'ido',
            r'ida$': 'ida',
            r'ante$': 'ante',
            r'ente$': 'ente',
            r'inte$': 'inte',
            r'ário$': 'ario',
            r'ária$': 'aria',
            r'ório$': 'orio',
            r'ória$': 'oria',
            r'eiro$': 'ero',
            r'eira$': 'era',
            r'ista$': 'ista',
            r'ismo$': 'ismo',
            r'eza$': 'eza',
            r'ura$': 'ura',
            r'agem$': 'aje',
            r'ção$': 'ción',
            r'são$': 'sión',
            r'al$': 'al',
            r'ar$': 'ar',
            r'er$': 'er',
            r'ir$': 'ir',
            r'or$': 'or',
            
            # Prefixos
            r'^des': 'des',
            r'^in': 'in',
            r'^im': 'im',
            r'^re': 're',
            r'^pre': 'pre',
            r'^sub': 'sub',
            r'^super': 'super',
            r'^inter': 'inter',
            r'^contra': 'contra',
            r'^anti': 'anti',
            r'^auto': 'auto',
            r'^semi': 'semi',
            r'^multi': 'multi',
            r'^ultra': 'ultra',
            r'^extra': 'extra',
            r'^trans': 'trans',
            r'^sobre': 'sobre',
            r'^entre': 'entre',
            
            # Substituições específicas
            r'nh': 'ñ',
            r'lh': 'll',
            r'ch': 'ch',
            r'qu': 'cu',
            r'gu': 'gu',
            r'ç': 'z',
            r'ss': 's',
            r'rr': 'rr',
            r'mm': 'm',
            r'nn': 'n',
            r'pp': 'p',
            r'tt': 't',
            r'cc': 'c',
            r'dd': 'd',
            r'ff': 'f',
            r'gg': 'g',
            r'll': 'll',
            r'bb': 'b',
            r'zz': 'z'
        }

    def traduzir_palavra(self, palavra):
        """Traduz uma palavra individual"""
        palavra_lower = palavra.lower()
        
        # Verifica no dicionário primeiro
        if palavra_lower in self.dicionario_pt_es:
            traducao = self.dicionario_pt_es[palavra_lower]
            # Mantém a capitalização original
            if palavra.isupper():
                return traducao.upper()
            elif palavra.istitle():
                return traducao.capitalize()
            else:
                return traducao
        
        # Aplica padrões de tradução
        palavra_traduzida = palavra_lower
        for padrao, substituicao in self.padroes_traducao.items():
            palavra_traduzida = re.sub(padrao, substituicao, palavra_traduzida)
        
        # Mantém a capitalização original
        if palavra.isupper():
            return palavra_traduzida.upper()
        elif palavra.istitle():
            return palavra_traduzida.capitalize()
        else:
            return palavra_traduzida

    def traduzir_texto(self, texto):
        """Traduz um texto completo"""
        if not texto or not texto.strip():
            return texto
        
        # Divide o texto em palavras mantendo pontuação
        palavras = re.findall(r'\w+|[^\w\s]', texto)
        
        texto_traduzido = []
        for palavra in palavras:
            if re.match(r'\w+', palavra):  # É uma palavra
                texto_traduzido.append(self.traduzir_palavra(palavra))
            else:  # É pontuação ou espaço
                texto_traduzido.append(palavra)
        
        return ''.join(texto_traduzido)

    def traduzir_docx(self, arquivo_entrada, arquivo_saida):
        """Traduz um arquivo DOCX completo preservando formatação e imagens"""
        print(f"🔄 Iniciando tradução de {arquivo_entrada} para {arquivo_saida}")
        
        try:
            # Carrega o documento
            doc = Document(arquivo_entrada)
            print(f"📄 Documento carregado com sucesso")
            
            # Conta elementos
            total_paragrafos = len(doc.paragraphs)
            total_tabelas = len(doc.tables)
            
            print(f"📊 Elementos encontrados:")
            print(f"   - Parágrafos: {total_paragrafos}")
            print(f"   - Tabelas: {total_tabelas}")
            
            # Traduz parágrafos
            print(f"🔤 Traduzindo parágrafos...")
            for i, paragrafo in enumerate(doc.paragraphs):
                if paragrafo.text.strip():
                    texto_original = paragrafo.text
                    texto_traduzido = self.traduzir_texto(texto_original)
                    
                    # Preserva a formatação aplicando a tradução run por run
                    if paragrafo.runs:
                        # Limpa o conteúdo mantendo a formatação
                        for run in paragrafo.runs:
                            run.text = ""
                        
                        # Adiciona o texto traduzido no primeiro run
                        if paragrafo.runs:
                            paragrafo.runs[0].text = texto_traduzido
                    else:
                        paragrafo.text = texto_traduzido
                
                # Progresso
                if (i + 1) % 50 == 0:
                    progresso = ((i + 1) / total_paragrafos) * 100
                    print(f"   📊 Progresso: {progresso:.1f}% ({i + 1}/{total_paragrafos})")
            
            # Traduz tabelas
            if total_tabelas > 0:
                print(f"📋 Traduzindo tabelas...")
                for i, tabela in enumerate(doc.tables):
                    for linha in tabela.rows:
                        for celula in linha.cells:
                            if celula.text.strip():
                                texto_original = celula.text
                                texto_traduzido = self.traduzir_texto(texto_original)
                                
                                # Preserva formatação da célula
                                for paragrafo in celula.paragraphs:
                                    if paragrafo.runs:
                                        for run in paragrafo.runs:
                                            run.text = ""
                                        if paragrafo.runs:
                                            paragrafo.runs[0].text = texto_traduzido
                                        break
                    
                    print(f"   📊 Tabela {i + 1}/{total_tabelas} traduzida")
            
            # Traduz cabeçalhos e rodapés
            print(f"📑 Traduzindo cabeçalhos e rodapés...")
            for secao in doc.sections:
                # Cabeçalho
                if secao.header:
                    for paragrafo in secao.header.paragraphs:
                        if paragrafo.text.strip():
                            texto_traduzido = self.traduzir_texto(paragrafo.text)
                            if paragrafo.runs:
                                for run in paragrafo.runs:
                                    run.text = ""
                                if paragrafo.runs:
                                    paragrafo.runs[0].text = texto_traduzido
                
                # Rodapé
                if secao.footer:
                    for paragrafo in secao.footer.paragraphs:
                        if paragrafo.text.strip():
                            texto_traduzido = self.traduzir_texto(paragrafo.text)
                            if paragrafo.runs:
                                for run in paragrafo.runs:
                                    run.text = ""
                                if paragrafo.runs:
                                    paragrafo.runs[0].text = texto_traduzido
            
            # Salva o documento traduzido
            print(f"💾 Salvando documento traduzido...")
            doc.save(arquivo_saida)
            
            # Verifica o arquivo criado
            if os.path.exists(arquivo_saida):
                tamanho = os.path.getsize(arquivo_saida)
                print(f"✅ Tradução concluída com sucesso!")
                print(f"📁 Arquivo salvo: {arquivo_saida}")
                print(f"📏 Tamanho: {tamanho:,} bytes ({tamanho/1024/1024:.1f} MB)")
                return True
            else:
                print(f"❌ Erro: Arquivo não foi criado")
                return False
                
        except Exception as e:
            print(f"❌ Erro durante a tradução: {str(e)}")
            return False

def main():
    """Função principal"""
    print("🇪🇸 TRADUTOR MANUAL PORTUGUÊS-ESPANHOL")
    print("=" * 50)
    
    # Arquivos
    arquivo_entrada = "MANUSCRITOPORTUGUES.docx"
    arquivo_saida = "MANUSCRITOPORTUGUES-ESPANHOL.docx"
    
    # Verifica se o arquivo de entrada existe
    if not os.path.exists(arquivo_entrada):
        print(f"❌ Erro: Arquivo {arquivo_entrada} não encontrado")
        return False
    
    # Cria o tradutor
    tradutor = TradutorManualEspanhol()
    
    # Executa a tradução
    inicio = datetime.now()
    sucesso = tradutor.traduzir_docx(arquivo_entrada, arquivo_saida)
    fim = datetime.now()
    
    duracao = fim - inicio
    print(f"⏱️ Tempo de execução: {duracao}")
    
    if sucesso:
        print(f"🎉 Tradução concluída com sucesso!")
        print(f"📄 Arquivo original: {arquivo_entrada}")
        print(f"📄 Arquivo traduzido: {arquivo_saida}")
        print(f"🔄 Próximo passo: Converter para EPUB KDP")
    else:
        print(f"❌ Falha na tradução")
    
    return sucesso

if __name__ == "__main__":
    main()